@echo off
REM n8n SDLC Integration Setup Script for Windows CMD
REM This script automates the entire setup process

setlocal enabledelayedexpansion

echo.
echo ================================================
echo n8n SDLC Integration - Automated Setup
echo ================================================
echo.

REM Check prerequisites
echo Checking prerequisites...

REM Check Node.js
where node >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] Node.js not found. Please install Node.js from https://nodejs.org
    exit /b 1
)
for /f "tokens=*" %%i in ('node --version') do set NODE_VERSION=%%i
echo [OK] Node.js found: %NODE_VERSION%

REM Check npm
where npm >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] npm not found. Please install npm
    exit /b 1
)
for /f "tokens=*" %%i in ('npm --version') do set NPM_VERSION=%%i
echo [OK] npm found: %NPM_VERSION%

REM Check Docker (optional)
where docker >nul 2>&1
if %errorlevel% neq 0 (
    echo [WARN] Docker not found. Skipping Docker setup.
    set SKIP_DOCKER=1
) else (
    for /f "tokens=*" %%i in ('docker --version') do set DOCKER_VERSION=%%i
    echo [OK] Docker found: %DOCKER_VERSION%
    set SKIP_DOCKER=0
)

echo.

REM Gather required information
if "%N8N_WEBHOOK_URL%"=="" (
    set /p N8N_WEBHOOK_URL="Enter your n8n webhook URL (e.g., http://localhost:5678): "
)

if "%GIT_PLATFORM_TOKEN%"=="" (
    set /p GIT_PLATFORM_TOKEN="Enter your Git platform token: "
)

if "%REPO_OWNER%"=="" (
    set /p REPO_OWNER="Enter repository owner/organization: "
)

if "%REPO_NAME%"=="" (
    set /p REPO_NAME="Enter repository name: "
)

if "%GIT_PLATFORM%"=="" (
    set /p GIT_PLATFORM="Enter Git platform (github or gitlab, default: github): "
    if "!GIT_PLATFORM!"=="" set GIT_PLATFORM=github
)

if "%SLACK_WEBHOOK_URL%"=="" (
    set /p SLACK_WEBHOOK_URL="Enter Slack webhook URL (optional, press Enter to skip): "
)

echo.

REM Step 1: Install n8n
echo Step 1: Setting up n8n...

if %SKIP_DOCKER%==0 (
    echo Installing n8n using Docker...
    
    docker ps -a --filter "name=n8n" --format "{{.Names}}" | findstr /C:"n8n" >nul 2>&1
    if %errorlevel% equ 0 (
        echo n8n container already exists. Starting it...
        docker start n8n
    ) else (
        echo Creating n8n container...
        docker run -d --name n8n -p 5678:5678 -v "%USERPROFILE%\.n8n:/home/node/.n8n" n8nio/n8n
    )
    
    echo [OK] n8n is running in Docker container
    echo Access n8n at: http://localhost:5678
    echo Waiting for n8n to start...
    timeout /t 10 /nobreak >nul
) else (
    echo Installing n8n globally using npm...
    call npm install -g n8n
    if %errorlevel% equ 0 (
        echo [OK] n8n installed successfully
        echo Start n8n with: n8n start
        echo [WARN] Make sure n8n is running before proceeding!
        set /p CONTINUE="Is n8n running? (y/n): "
        if /i not "!CONTINUE!"=="y" (
            echo [ERROR] Please start n8n first and run this script again
            exit /b 1
        )
    ) else (
        echo [ERROR] Failed to install n8n
        exit /b 1
    )
)

echo.

REM Step 2: Install project dependencies
echo Step 2: Installing project dependencies...

if exist package.json (
    call npm install
    echo [OK] Dependencies installed
) else (
    echo [WARN] No package.json found. Skipping npm install...
)

echo.

REM Step 3: Create .env file
echo Step 3: Creating environment configuration...

set WEBHOOK_SECRET=%RANDOM%%RANDOM%%RANDOM%

(
echo # n8n SDLC Integration - Environment Variables
echo # Generated by setup script
echo.
echo # Git Platform Configuration
echo GIT_PLATFORM_TOKEN=%GIT_PLATFORM_TOKEN%
echo GIT_PLATFORM=%GIT_PLATFORM%
echo REPO_OWNER=%REPO_OWNER%
echo REPO_NAME=%REPO_NAME%
echo.
echo # n8n Configuration
echo N8N_WEBHOOK_URL=%N8N_WEBHOOK_URL%
echo WEBHOOK_SECRET=%WEBHOOK_SECRET%
echo.
echo # CI/CD Platform Configuration ^(configure as needed^)
echo CI_PLATFORM_API_URL=
echo CI_PLATFORM_API_KEY=
echo.
echo # Communication Platforms
echo SLACK_WEBHOOK_URL=%SLACK_WEBHOOK_URL%
echo MICROSOFT_TEAMS_WEBHOOK_URL=
echo.
echo # Issue Tracking ^(configure as needed^)
echo JIRA_URL=
echo JIRA_EMAIL=
echo JIRA_API_TOKEN=
) > .env

echo [OK] Created .env file
echo.

REM Step 4: Import workflows
echo Step 4: Importing n8n workflows...

echo To import workflows:
echo 1. Open n8n UI at %N8N_WEBHOOK_URL%
echo 2. Go to 'Workflows' -^> 'Import from File'
echo 3. Import each file from the workflows\ directory
echo.

REM Step 5: Setup webhooks
echo Step 5: Setting up webhooks...

if "%SKIP_WEBHOOK%"=="" (
    echo Configuring webhook in Git platform...
    
    set N8N_WEBHOOK_URL=%N8N_WEBHOOK_URL%
    set GIT_PLATFORM_TOKEN=%GIT_PLATFORM_TOKEN%
    set REPO_OWNER=%REPO_OWNER%
    set REPO_NAME=%REPO_NAME%
    set GIT_PLATFORM=%GIT_PLATFORM%
    
    call node scripts/setup-webhook.js create
    if %errorlevel% equ 0 (
        echo [OK] Webhook configured successfully
    ) else (
        echo [WARN] Webhook setup failed. You may need to configure it manually:
        echo   - Go to your repository -^> Settings -^> Webhooks
        echo   - Add webhook URL: %N8N_WEBHOOK_URL%/webhook/git-webhook
        echo   - Select events: Push, Pull request
    )
) else (
    echo Skipping webhook setup
)

echo.

REM Step 6: Test integration
echo Step 6: Testing integration...

echo To test, send POST request to: %N8N_WEBHOOK_URL%/webhook/feature-request
echo.
echo Example test payload:
echo {
echo   "action": "create_feature",
echo   "repository": "%REPO_OWNER%/%REPO_NAME%",
echo   "feature_name": "test-feature",
echo   "ticket_id": "TEST-123",
echo   "feature_type": "api",
echo   "description": "Test feature",
echo   "developer": "%USERNAME%@company.com"
echo }
echo.

REM Summary
echo ================================================
echo [OK] Setup completed successfully!
echo ================================================
echo.
echo Next steps:
echo 1. Import workflows in n8n UI: %N8N_WEBHOOK_URL%
echo 2. Configure credentials in n8n ^(GitHub, Slack, etc.^)
echo 3. Test the integration
echo 4. Review documentation: README.md, QUICKSTART.md
echo.
echo Workflows to import:
echo   - workflows\feature-automation.json
echo   - workflows\ci-cd-integration.json
echo   - workflows\notifications.json
echo   - workflows\code-quality.json
echo.
echo Configuration file: .env
echo.
echo Happy automating! 🚀
echo.

endlocal

